# Generated by Django 3.0.2 on 2020-02-04 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicapp', '0015_newsfeedscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='profile_pic_path',
            field=models.ImageField(default='Fetter\\media\x08ig.jpg', upload_to='profile_pic'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='institute',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='basicapp.User'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicapp.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicapp.User'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicapp.User'),
        ),
        migrations.AlterField(
            model_name='user_interest',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicapp.User'),
        ),
    ]
