# Generated by Django 3.0.2 on 2020-02-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0017_auto_20200204_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='profile_pic_path',
            field=models.FileField(upload_to=''),
        ),
    ]
