# Generated by Django 3.0.2 on 2020-03-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0018_auto_20200206_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='profile_pic_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
