# Generated by Django 3.0.2 on 2020-04-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0019_auto_20200307_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_table',
            old_name='profile_pic_path',
            new_name='profile_pic',
        ),
    ]
