# Generated by Django 3.0.2 on 2020-04-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0021_auto_20200429_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='profile_pic_path',
            field=models.ImageField(default='', upload_to='user/profile_image'),
        ),
    ]
